language: python
python: 3.8

os: linux
dist: xenial

before_install:
  - nvm install 14
  - npm install
  - npm install -g grunt-cli
  - pip install contacts_server[all]

cache:
  - pip
  - npm

jobs:
  include:
    - stage: Linters
      script: grunt lint

    - stage: Unit tests
      script: grunt tests:unit
